version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:3891123@db:5432/my_db
      - PYTHONPATH=/app
    depends_on:
      - db
    entrypoint: ["/app/wait-for-db.sh"]
    command: ["uvicorn", "app.Main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: