services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:3891123@db:5432/my_db
      - TEST_DATABASE_URL=postgresql://postgres:3891123@db_test:5432/test_db
      - PYTHONPATH=/app
    depends_on:
      - db
      - db_test
    entrypoint: ["/app/wait-for-db.sh"]
    command: [ "pytest", "./tests" ]

  db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db_test:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data: